// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjuiwvmcnhqgndrhnmvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdWl3dm1jbmhxZ25kcmhubXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTcyNDksImV4cCI6MjA2MjUzMzI0OX0.vSsbwyxRcuvRkz1Mw1xSUvHtpJZL2UygPkzEX7plaLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);